### ISSUE TITLE
Expose an API method for script analysis

### ISSUE THREAD

**Issue by alexo** [jknack/amd4j#1]
it would really help if the amd4j would allow client code to collect easily the dependencies using the following API:

 amd4j.analyze(script) : AmdResult

where the script can be String, Reader or InputStream and AmdResult contains the analysis results like (dependencies, scriptId, etc).

**Comment by jknack** [comment]
one small comment, resource resolution is done by a `ResourceLoader` which can read from classpath, filesystem, webcontext, etc... So, your comment: _script can be String, Reader or InputStream_ will be provided by `ResourceLoader` implementation

Here is an example:

``` java
  Module result = new Optimizer().analyze(new Config("module.js")));

  // print graph
  System.out.println(result.toStringTree());

  // get dependencies
  Iterable<Module> dependencies = result.getDependencies(false);

  // get transitive dependencies
  Iterable<Module> dependencies = result.getDependencies(true);
```

**Comment by alexo** [comment]
The current implementation is good, but it doesn't do exactly what would I expect. 
It assumes that all resources can be located using ResourceLoader, which is a good thing, but doesn't allow client code easily to plug in custom locator. What I actually need, is a class which just analyzes the script content without any assumption regarding the script location. 

This would allow the class to focus on analysis only (separation of concerns), while more advanced module retrieval would be performed by another class.. 

Let me know if you think I need to elaborate or if you don't think that does make sense...

Thanks,
Alex

**Comment by jknack** [comment]
You can plug in a custom locator by:

``` java
   Module result = new Amd4j().with(new CustomLoader()).analyze(new Config("module.js")));
```

I'm not sure if a dependency analysis make sense without resolving the script/dependencies.

For example:

z.js:

``` js
define(["x", "y"], function() {
 ...
});
```

I need to _resolve x (or y) to a location_ bc I need to analyze what dependencies _x and y_ need?
Also, I need to make sure that x and y are present, if not this need to be translated to a _dependency not found error_

`require.js` has a path alias feature that let you say I want "x" but "x" is here "/js/x/x.js". So, "x" is an alias for "/js/x/x.js".

Finally, there is a `shim` option which convert `browser global scripts` into AMD scripts.

That is the whole pic and that is why I think script resolution and loading is necessary.

Now, if the only thing you want if getting "x" & "y", you can try with [DependencyCollector#collect(Config, Module)](https://github.com/jknack/amd4j/blob/master/amd4j-core/src/main/java/com/github/jknack/amd4j/DependencyCollector.java#L58)

Let me know if `DependencyCollector#collect` is all that you need and will make it public.

Thanks

**Comment by alexo** [comment]
Probably I'll close this issue until I have a more clear idea regarding what I need. I'm trying to figure out the best way to integrate amd4j in wro4j. I'm not yet sure what is the best approach. If you have any suggestions, please let me know.

Thanks,
Alex
